name: .NET Core for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0    

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: dotnet restore -r linux-x64 ScepClient.csproj
    - name: Build
      run: dotnet build -p:Version=1.2.$GITHUB_RUN_NUMBER.500 --configuration Release --no-restore -r linux-x64 ScepClient.csproj
    - name: Publish
      run: dotnet publish -p:Version=1.2.$GITHUB_RUN_NUMBER.500 --configuration Release --no-restore -r linux-x64 -p:PublishSingleFile=true --self-contained false ScepClient.csproj
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: scepclient-linux-x64
        path: bin/Release/net6.0/linux-x64/publish/*